import { useState, useRef } from 'react'
import { motion } from 'framer-motion'
import { toast } from 'react-hot-toast'
import { ArrowLeft, Download, Lightbulb, BookOpen, Shield, Award, AlertTriangle } from 'lucide-react'
import CircularScore from '../components/CircularScore'
import { SkillRadarChart, SkillBarChart } from '../components/SkillCharts'
import { MatchedSkills, MissingSkills, ExtraSkills } from '../components/SkillTags'

const fadeUp = {
  hidden: { opacity: 0, y: 20 },
  show: (i) => ({ opacity: 1, y: 0, transition: { delay: i * 0.08 } })
}

export default function AnalysisPage({ result, onNavigate }) {
  const [downloading, setDownloading] = useState(false)
  const reportRef = useRef(null)

  if (!result) {
    return (
      <div className="flex flex-col items-center justify-center h-full gap-4">
        <AlertTriangle size={40} className="text-amber-500" />
        <p className="text-slate-500">No analysis results yet.</p>
        <button onClick={() => onNavigate('dashboard')} className="btn-primary">Go to Dashboard</button>
      </div>
    )
  }

  const handleDownload = async () => {
    setDownloading(true)
    try {
      const html2pdf = (await import('html2pdf.js')).default
      const element = reportRef.current
      if (!element) { toast.error('Report not ready.'); return }

      const opt = {
        margin: [8, 8, 8, 8],
        filename: `resume_analysis_${result.job_role.replace(/ /g, '_')}.pdf`,
        image: { type: 'jpeg', quality: 0.97 },
        html2canvas: {
          scale: 2,
          useCORS: true,
          letterRendering: true,
          backgroundColor: '#f8fafc',
          scrollY: 0,
        },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        pagebreak: { mode: ['avoid-all', 'css', 'legacy'] },
      }

      await html2pdf().set(opt).from(element).save()
      toast.success('Report with charts downloaded!')
    } catch (e) {
      console.error(e)
      toast.error('Download failed. Try again.')
    } finally {
      setDownloading(false)
    }
  }

  return (
    <div className="p-8 max-w-7xl mx-auto">
      {/* Page header — NOT included in PDF */}
      <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}
        className="flex items-center justify-between mb-8">
        <div className="flex items-center gap-4">
          <button onClick={() => onNavigate('dashboard')}
            className="p-2 rounded-xl bg-white border border-slate-200 hover:bg-slate-50 text-slate-500 hover:text-slate-800 transition-colors shadow-sm">
            <ArrowLeft size={18} />
          </button>
          <div>
            <h1 className="text-2xl font-bold text-slate-800">Analysis Results</h1>
            <p className="text-sm text-slate-400">{result.job_role} • {result.word_count} words extracted</p>
          </div>
        </div>
        <motion.button whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }}
          onClick={handleDownload} disabled={downloading}
          className="btn-primary flex items-center gap-2 text-sm">
          <Download size={16} />
          {downloading ? 'Capturing charts...' : 'Download Report'}
        </motion.button>
      </motion.div>

      {/* ── Everything below is captured into the PDF ── */}
      <div ref={reportRef} className="bg-slate-50 rounded-2xl p-6 space-y-6">

        {/* PDF title header */}
        <div className="flex items-start justify-between pb-4 border-b border-slate-200">
          <div>
            <h2 className="text-xl font-bold text-slate-800">Resume Skill Gap Analysis</h2>
            <p className="text-sm text-slate-400 mt-0.5">
              Target Role: <span className="font-semibold text-slate-600">{result.job_role}</span>
              &nbsp;•&nbsp;{result.word_count} words extracted
            </p>
          </div>
          <div className="text-right">
            <p className="text-xs text-slate-400">Generated by AI Resume Analyzer</p>
            <p className="text-xs text-slate-400">{new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
          </div>
        </div>

        {/* Score Cards */}
        <div className="grid grid-cols-3 gap-4">
          <div className="bg-white rounded-2xl p-6 flex flex-col items-center justify-center shadow-sm border border-slate-100">
            <CircularScore score={result.match_score} label="Match Score" />
            <p className="text-xs text-slate-400 mt-3 text-center max-w-[140px]">{result.role_description}</p>
          </div>

          <div className="bg-white rounded-2xl p-6 flex flex-col items-center justify-center shadow-sm border border-slate-100">
            <CircularScore score={result.resume_score} label="Resume Score" />
            <div className="mt-4 w-full space-y-2">
              <div className="flex justify-between text-xs text-slate-400">
                <span>Skills matched</span>
                <span className="text-slate-700 font-medium">{result.total_matched}/{result.total_required}</span>
              </div>
              <div className="h-1.5 bg-slate-100 rounded-full overflow-hidden">
                <div
                  className="h-full bg-gradient-to-r from-primary-500 to-violet-500 rounded-full"
                  style={{ width: `${(result.total_matched / result.total_required) * 100}%` }}
                />
              </div>
            </div>
          </div>

          <div className="bg-white rounded-2xl p-6 shadow-sm border border-slate-100 space-y-3">
            <h3 className="text-sm font-semibold text-slate-700 flex items-center gap-2">
              <Award size={15} className="text-amber-500" />
              Quick Stats
            </h3>
            {[
              { label: 'Matched Skills', value: result.matched_skills.length, color: 'text-emerald-600', bg: 'bg-emerald-50' },
              { label: 'Missing Skills', value: result.missing_skills.length, color: 'text-red-600', bg: 'bg-red-50' },
              { label: 'Bonus Skills', value: result.extra_skills.length, color: 'text-blue-600', bg: 'bg-blue-50' },
              { label: 'Core Skills Hit', value: result.core_matched.length, color: 'text-violet-600', bg: 'bg-violet-50' },
            ].map((s) => (
              <div key={s.label} className={`flex items-center justify-between px-3 py-1.5 rounded-xl ${s.bg}`}>
                <span className="text-xs text-slate-500">{s.label}</span>
                <span className={`text-sm font-bold ${s.color}`}>{s.value}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Charts — rendered inline so html2canvas captures them */}
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-white rounded-2xl p-4 shadow-sm border border-slate-100">
            <SkillRadarChart
              matched={result.total_matched}
              missing={result.missing_skills.length}
              total={result.total_required}
            />
          </div>
          <div className="bg-white rounded-2xl p-4 shadow-sm border border-slate-100">
            <SkillBarChart
              matchedSkills={result.matched_skills}
              missingSkills={result.missing_skills}
            />
          </div>
        </div>

        {/* Skills */}
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-white rounded-2xl p-5 shadow-sm border border-slate-100 space-y-5">
            <MatchedSkills skills={result.matched_skills} />
            {result.extra_skills.length > 0 && (
              <div className="border-t border-slate-100 pt-4">
                <ExtraSkills skills={result.extra_skills} />
              </div>
            )}
          </div>
          <div className="bg-white rounded-2xl p-5 shadow-sm border border-slate-100">
            <MissingSkills skills={result.missing_skills} />
          </div>
        </div>

        {/* Suggestions + Courses + ATS */}
        <div className="grid grid-cols-3 gap-4">
          <div className="bg-white rounded-2xl p-5 shadow-sm border border-slate-100">
            <h3 className="text-sm font-semibold text-slate-700 mb-3 flex items-center gap-2">
              <Lightbulb size={14} className="text-amber-500" />
              AI Suggestions
            </h3>
            <div className="space-y-2.5">
              {result.suggestions.map((s, i) => (
                <div key={i} className="flex gap-2.5">
                  <div className="w-5 h-5 rounded-full bg-amber-100 text-amber-600 text-xs flex items-center justify-center shrink-0 font-bold">
                    {i + 1}
                  </div>
                  <p className="text-xs text-slate-500 leading-relaxed">{s}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-white rounded-2xl p-5 shadow-sm border border-slate-100">
            <h3 className="text-sm font-semibold text-slate-700 mb-3 flex items-center gap-2">
              <BookOpen size={14} className="text-primary-600" />
              Recommended Courses
            </h3>
            <div className="space-y-2.5">
              {result.courses.map((c, i) => (
                <div key={i} className="p-2.5 rounded-xl bg-slate-50 border border-slate-200">
                  <div className="flex items-start justify-between gap-1">
                    <p className="text-xs font-semibold text-slate-700 leading-tight">{c.title}</p>
                    <span className="text-xs px-1.5 py-0.5 rounded-full bg-primary-100 text-primary-600 shrink-0">{c.level}</span>
                  </div>
                  <p className="text-xs text-slate-400 mt-0.5">{c.platform} • {c.skill}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-white rounded-2xl p-5 shadow-sm border border-slate-100">
            <h3 className="text-sm font-semibold text-slate-700 mb-3 flex items-center gap-2">
              <Shield size={14} className="text-emerald-600" />
              ATS Optimization
            </h3>
            <div className="space-y-2.5">
              {result.ats_tips.map((tip, i) => (
                <div key={i} className="flex gap-2">
                  <div className="w-1.5 h-1.5 rounded-full bg-emerald-400 shrink-0 mt-1.5" />
                  <p className="text-xs text-slate-500 leading-relaxed">{tip}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="pt-4 border-t border-slate-200 text-center">
          <p className="text-xs text-slate-400">Generated by AI Resume Skill Gap Analyzer • Powered by spaCy NLP + TF-IDF</p>
        </div>
      </div>
    </div>
  )
}
